name = "decole-links-redirect"
main = "src/index.ts"
compatibility_date = "2026-02-05"
workers_dev = false
routes = [
  { pattern = "links.decolesuacarreiraesg.com.br/*", zone_name = "decolesuacarreiraesg.com.br" }
]

[observability]
  [observability.logs]
  enabled = false
  invocation_logs = true

[vars]
ELIZETE_WHATSAPP_NUMBER = "351915787088"
ELIZETE_WHATSAPP_DEFAULT_TEXT = "Olá Elizete, estou no site do decolesuacarreiraesg.com.br e tenho uma dúvida. :)"
CHECKOUT_URL = "https://pay.hotmart.com"