name = "decole-links-redirect"
main = "src/index.ts"
compatibility_date = "2026-02-05"
workers_dev = false
routes = [
  { pattern = "links.decolesuacarreiraesg.com.br/*", zone_name = "decolesuacarreiraesg.com.br" }
]

[[queues.producers]]
binding = "FUNNEL_EVENTS"
queue = "decole-q-funnel-events"

[[kv_namespaces]]
binding = "IDENTITY_KV"
id = "88989e2e3492459eadb06e9da523dfae"

[observability]
  [observability.logs]
  enabled = false
  invocation_logs = true

[vars]
ELIZETE_WHATSAPP_NUMBER = "351915787088"
ELIZETE_WHATSAPP_DEFAULT_TEXT = "Olá Elizete, estou no site do decolesuacarreiraesg.com.br e tenho uma dúvida. :)"
DECOLE_MENTORIA_CHECKOUT_URL = "https://pay.hotmart.com/K98068530F?off=3j6lto4t"
PLANO_DE_VOO_CHECKOUT_URL = "https://pay.hotmart.com/R105463680A?off=f3yweqek"
LINKS_PRODUCTS = "[{\"checkoutPath\":\"/decole-esg/checkout\",\"checkoutBaseUrl\":\"https://pay.hotmart.com/K98068530F?off=3j6lto4t\",\"productCode\":\"DECOLE_ESG_MENTORIA\"},{\"checkoutPath\":\"/plano-de-voo/checkout\",\"checkoutBaseUrl\":\"https://pay.hotmart.com/R105463680A?off=f3yweqek\",\"productCode\":\"DECOLE_PLANOVOO\"}]"
