name = "decole-brevo-form"
main = "src/index.js"
compatibility_date = "2025-01-01"

[triggers]
routes = [
  "https://forms.decolesuacarreiraesg.com.br/brevo*"
]

[vars]
ALLOWED_ORIGIN = "https://decolesuacarreiraesg.com.br"
BREVO_LIST_ID = "7"
