name = "decole-brevo-worker"
main = "src/index.js"
compatibility_date = "2025-01-01"
workers_dev = false
routes = [
  "forms.decolesuacarreiraesg.com.br/brevo*"
]

[vars]
ALLOWED_ORIGIN = "https://decolesuacarreiraesg.com.br"
BREVO_LIST_ID = "7"
BREVO_DOI_TEMPLATE_ID = "1"
POST_SUBMIT_REDIRECT_URL = "https://pay.hotmart.com/K98068530F?off=1myrvww7"
