name = "decole-brevo-worker"
main = "src/index.js"
compatibility_date = "2025-01-01"
workers_dev = false
routes = [
  "forms.decolesuacarreiraesg.com.br/brevo*"
]

[vars]
ALLOWED_ORIGIN = "https://decolesuacarreiraesg.com.br"
BREVO_LIST_ID = "7"
