name = "decole-jobs-events-consumer"
main = "src/index.ts"
compatibility_date = "2026-02-05"
workers_dev = true

[[queues.consumers]]
queue = "decole-q-hotmart-events"
max_batch_size = 25
max_batch_timeout = 10
max_retries = 5
dead_letter_queue = "decole-q-hotmart-events-dlq"

[observability]
  [observability.logs]
  enabled = false
  invocation_logs = true

[[kv_namespaces]]
binding = "DEDUPE_KV"
id = "f928a6e6eed541f6b84a94c67dd15480"

[vars]
HOTMART_PRODUCTS = "[{\"id\":5083704,\"name\":\"DECOLE sua Carreira ESG\",\"prefix\":\"DECOLE_ESG\",\"checkoutCode\":\"K98068530F\",\"offerCode\":\"3j6lto4t\"}]"
BREVO_CART_ABANDONMENT_TEMPLATE_ID = "8"
BREVO_REPLY_TO_EMAIL = "contato@decolesuacarreiraesg.com.br"
