name = "decole-api-hotmart-webhook"
main = "src/index.ts"
compatibility_date = "2026-02-05"
workers_dev = false
routes = [
  { pattern = "api.decolesuacarreiraesg.com.br/webhooks/hotmart*", zone_name = "decolesuacarreiraesg.com.br" }
]

[[queues.producers]]
binding = "HOTMART_EVENTS"
queue = "decole-q-hotmart-events"

[observability]
  [observability.logs]
  enabled = false
  invocation_logs = true
