name = "decole-api-external-webhooks"
main = "src/index.ts"
compatibility_date = "2026-02-05"
workers_dev = false
routes = [
  { pattern = "api.decolesuacarreiraesg.com.br/webhooks/hotmart*", zone_name = "decolesuacarreiraesg.com.br" },
  { pattern = "api.decolesuacarreiraesg.com.br/webhooks/v1/*", zone_name = "decolesuacarreiraesg.com.br" }
]

[[queues.producers]]
binding = "HOTMART_EVENTS"
queue = "decole-q-hotmart-events"

[observability]
  [observability.logs]
  enabled = false
  invocation_logs = true

[vars]
WEBHOOK_FORWARDING_RULES = "[{\"productSlug\":\"planodevoo\",\"subsystem\":\"hotmart\",\"targetUrl\":\"https://n8n.decolesuacarreiraesg.com.br/webhook/plano-de-voo/hotmart\",\"required\":true}]"
